on:
  push:
    branches:
      - integ-tests

name: Integration Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Print current build ID
      run: |
        echo Integration test run: githubactionsamazonecsdeplo-q0a9Gc4Dsaz2:83003244-3152-4b9a-93b2-960d604cef15

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@3046f7d94915e17365d22d80da336cc92e5fdddb
      with:
        task-definition: task-definition.json
        service: github-actions-deploy-task-def-integ-test
        cluster: github-actions-deploy-task-def-integ-test
        wait-for-service-stability: true
