on:
  push:
    branches:
      - integ-tests

name: Integration Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Print current build ID
      run: |
        echo Integration test run: githubactionsamazonecsdeplo-q0a9Gc4Dsaz2:7d15179a-894a-4eaf-a098-a2a207560572

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@d2fcbd93ba9863e18d5061993f82ea608873d77d
      with:
        task-definition: task-definition.json
        service: github-actions-deploy-task-def-integ-test
        cluster: github-actions-deploy-task-def-integ-test
        wait-for-service-stability: true
